name:                prover
version:             0.1.0.0
github:              "githubuser/prover"
author:              "Marta Nowakowska"
copyright:           "2021 Marta Nowakowska"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/prover#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- parsec
- random
- mtl
- hashable
- unordered-containers

library:
  source-dirs: src

executables:
  prover-exe:
    main:                FO-prover.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prover
